openapi: 3.0.0
x-stoplight:
  id: 3nevh0d5n4ijq
info:
  description: Search for Proposal Status
  version: '1.0'
  title: Search for Proposal Status
  termsOfService: 'urn:tos'
  contact:
    name: First Data
    url: 'https://www.firstdata.com/pt_br/home.html'
  license:
    name: Licença - Open Source
    url: 'https://www.firstdata.com/pt_br/home.html'
servers:
  - url: 'https://cat.api.firstdata.com'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Search for Proposal Status
paths:
  '/bwa/proposta/status/{inst}/{doc}':
    get:
      tags:
        - Online Boarding
      x-proxy-name: Proposal Status - Consult (Out of Online Boarding)
      x-group-name: Online Boarding
      x-child-product-name: Digital Solutions
      description: Search for Proposal Status
      summary: Search for Proposal Status
      operationId: searchForProposalStatus
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: 'null'
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: '1563309156733'
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: doc
          in: path
          description: Tax ID (CPF/CNPJ) to be searched
          required: true
          schema:
            type: string
        - name: inst
          in: path
          description: Merchant Institution Number
          example: '00000003'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjetoStatusResponse'
      deprecated: false
components:
  schemas:
    ObjetoStatusResponse:
      type: object
      properties:
        codigoRetorno:
          type: string
          description: Returnd Code
          example: '00 - Successfully Done'
          enum:
            - 00 - Successfully Done
            - 01 - System Error
        descricaoRetorno:
          type: string
          description: Descrição do Retorno.
          example: 00 - Successfully Done
          enum:
            - 00 - Successfully Done
            - 01 - System Error
        propostas:
          type: array
          items:
            $ref: '#/components/schemas/Proposta'
      title: ObjetoStatusResponse
      xml:
        name: response
        attribute: false
        wrapped: false
      x-stoplight:
        id: fexvnoh11f297
    Proposta:
      type: object
      properties:
        numeroProposta:
          type: string
          description: Boarding Proposal Number
          example: '979102119213298000432'
        dataProposta:
          type: string
          description: Proprosal Sent Date
          example: YYYYMMDD
        codigoMotivoRejeicao:
          type: string
          description: Rejection Reason Code
          example: ''
        descricaoMotivoRejeicao:
          type: string
          description: Reason Code Description
          example: ''
        numeroMerchant:
          type: string
          description: Merchant Code
          example: '40929598'
        codigoCredenciador:
          type: string
          description: Boarding Code
          example: '1'
        indicadorEcommerce:
          type: string
          description: E-Commercer Indicator
          example: '1 - No'
          enum:
            - 1 - No
            - 0 - Yes
        statusPropostas:
          type: array
          items:
            $ref: '#/components/schemas/StatusProposta'
      title: Proposta
      xml:
        name: proposta
        attribute: false
        wrapped: false
      x-stoplight:
        id: 83o1t9kp66m9n
    StatusProposta:
      type: object
      properties:
        codigoStatusProposta:
          type: string
          description: Proposal Status Code. It will return only the code
          example: '0 Affiliated'
          enum:
            - '-1 Not found'
            - 0 Affiliated
            - 1 Validation Error
            - 2 Rejected Credit
            - 3 Boarding Failure
            - 4 File Structure record with errors
            - 5 Pending QC
            - 6 Rejected QC
            - 7 Pending Credit
            - 8 Approved Credit
            - 9 In Progress
            - 11 Pending credit submission
            - 12 Pending Serpro submission
            - 13 Approved Serpro
            - 14 Rejected Serpro
            - 15 Rejected TMS
            - 16 Expired due to lack of payment
            - 17 Rejected due to rejected payment
            - 18 Pending Boarding submission
            - 19 Awaiting bankworks answer
            - 20 Boarding file error
            - 21 Pending merchant id
            - 22 Pending Restriction Verification
            - 23 Rejected Restriction Verification
            - 24 Rejected Serpro
            - 25 Rejected Serpro
            - 26 Pending analysis compliance
            - 27 Rejected by compliance
            - 28 Approved by compliance
            - 29 Expired Analysis Compliance
            - 30 C&R- Pending Manual Review
            - 31 Pending New Device
            - 32 Pending Consult OS
            - 33 Pending Terminal Validation
            - 34 Rejected Terminal Validation
            - 35 Pending analysis Pricing
            - 36 Approved by Pricing
            - 37 Rejected by Pricing
            - 38 Serpro Unavaliable
            - 77 Pending QC
            - 260 QC Edit
            - 270 QC Submitted
            - 400 Boarded to BWA
            - 500 Boarding Failure
            - 765 Credit Approved
            - 768 Credit Declined
            - 769 CO Comments Required
            - 860 PrePayment Pending
            - 870 PrePayment Approved
            - 880 PrePayment Declined
            - 888 QC Approved
            - 999 QC Declined
        descricaoStatusProposta:
          type: string
          description: Proposal Status Description
          example: 0 Affiliated
          enum:
            - '-1 Not found'
            - 0 Affiliated
            - 1 Validation Error
            - 2 Rejected Credit
            - 3 Boarding Failure
            - 4 File Structure record with errors
            - 5 Pending QC
            - 6 Rejected QC
            - 7 Pending Credit
            - 8 Approved Credit
            - 9 In Progress
            - 11 Pending credit submission
            - 12 Pending Serpro submission
            - 13 Approved Serpro
            - 14 Rejected Serpro
            - 15 Rejected TMS
            - 16 Expired due to lack of payment
            - 17 Rejected due to rejected payment
            - 18 Pending Boarding submission
            - 19 Awaiting bankworks answer
            - 20 Boarding file error
            - 21 Pending merchant id
            - 22 Pending Restriction Verification
            - 23 Rejected Restriction Verification
            - 24 Rejected Serpro
            - 25 Rejected Serpro
            - 26 Pending analysis compliance
            - 27 Rejected by compliance
            - 28 Approved by compliance
            - 29 Expired Analysis Compliance
            - 30 C&R- Pending Manual Review
            - 31 Pending New Device
            - 32 Pending Consult OS
            - 33 Pending Terminal Validation
            - 34 Rejected Terminal Validation
            - 35 Pending analysis Pricing
            - 36 Approved by Pricing
            - 37 Rejected by Pricing
            - 38 Serpro Unavaliable
            - 77 Pending QC
            - 260 QC Edit
            - 270 QC Submitted
            - 400 Boarded to BWA
            - 500 Boarding Failure
            - 765 Credit Approved
            - 768 Credit Declined
            - 769 CO Comments Required
            - 860 PrePayment Pending
            - 870 PrePayment Approved
            - 880 PrePayment Declined
            - 888 QC Approved
            - 999 QC Declined
        dataStatusProposta:
          type: string
          description: Proposal Status Date
          example: YYYYMMDD
      title: StatusProposta
      xml:
        name: status
        attribute: false
        wrapped: false
      x-stoplight:
        id: 0b4lhisn80qmn
