openapi: 3.0.2
info:
  description: Request of Device Paper Roll
  version: "1.0"
  title: Request of Device Paper Roll
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Request of Device Paper Roll
    description: Request of Device Paper Roll
paths:
  "/bwa/solicitabobina/{instituicao}/{merchant}/{logico}":
    get:
      tags:
        - Request of Device Paper Roll
      x-proxy-name: Request of Device Paper Roll
      x-group-name: Devices Information
      x-child-product-name: Digital Solutions
      description: Paper Roll - Request
      summary: Request of Device Paper Roll
      operationId: requestOfDevicePapreRoll
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: ''
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch format
          required: true
          example: '1563309156733'
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: instituicao
          in: path
          description: Merchant Institution Number
          example: "00000003"
          required: true
          schema:
            type: string
        - name: merchant
          in: path
          description: Merchant Code
          required: true
          example: "91002806"
          schema:
            type: string
        - name: logico
          in: path
          description: Device Logical Number
          example: "1234567890"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Response:
      type: object
      description: "It is allowed to request Paper Roll when logic number starts with 'PGW', 'ETD', 'GPR', 'EGD', 'PMP', 'WIF' and 'PFT'"
      properties:
        numeroMerchant:
          type: string
          description: Merchant Code
          example: "91002806"
        numeroLogico:
          type: string
          description: Device Logical Number
          example: "1234567890"
        prazoEntrega:
          type: string
          description: Delivery Date information
          example: "20191010"
        codigoRetorno:
          type: string
          description: Return Code
          enum:
            - 00 – Solicitação incluída com sucesso (meaning Request Successfully Completed)
            - 01 – Estabelecimento não encontrado (meaning Merchant did not find)
            - 02 – Estabelecimento não pertence à base requisitante (meaning Combination of Institution and Merchant did not match)
            - 03 – Terminal não encontrado (meaning Device did not find)
            - 04 – Terminal não pode requisitar bobina (meaning Paper Roll cannot be requested)
        descricaoRetorno:
          type: string
          description: Return Description
          enum:
            - 00 – Solicitação incluída com sucesso (meaning Request Successfully Completed)
            - 01 – Estabelecimento não encontrado (meaning Merchant did not find)
            - 02 – Estabelecimento não pertence à base requisitante (meaning Combination of Institution and Merchant did not match)
            - 03 – Terminal não encontrado (meaning Device did not find)
            - 04 – Terminal não pode requisitar bobina (meaning Paper Roll cannot be requested)
