version: 1.0.0
recipes:
- link: recipes/Recipe-1.md
  title: Message signature
  type: recipe
- link: recipes/Recipe-2.md
  title: Make a card payment
  type: recipe
- link: recipes/Recipe-3.md
  title: Refund a transaction
  type: recipe
