openapi: 3.0.2
info:
  description: Historico de Contrato
  version: "1.0"
  title: Historico de Contrato
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-header-api-key: 'X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
x-header-api-secret: 'N93nmFmoY0NzSMC5'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Historico de Contrato
paths:
  /bwa/historico-contrato/v1/historicoContrato:
    get:
      tags:
        - Historico de Contrato
      x-proxy-name: Historic Contract
      x-group-name: Merchant Information & Cases
      x-child-product-name: Digital Solutions
      description: Historic Contract
      summary: Merchant Information & Cases
      operationId: searchForAvailableDevicesByMerchantCode
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: instituicao
          in: header
          description: 'Merchant Institution Number'
          required: true
          example: '00000003'
          schema:
            type: string
        - name: estabelecimento
          in: header
          description: Merchant Code
          required: true
          example: '24041964'
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        '400':
          description: Invalid Information
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    DResponse:
      type: object
      properties:
        codigoRetorno:
          type: integer
          format: int32
          example: 0
          description: Return Code
          enum:
            - 0
            - 1
        mensagem:
          type: string
          description: Return Message
          example: Error Message
          enum:
            - Successfully Done
            - Invalid Request Information (Institution, merchant ou service-contract) (400 BAD REQUEST)
        conteudo:
          type: array
          description: List of Historic contracts
          items:
            $ref: '#/components/schemas/historicoContrato'
      title: DResponse
    historicoContrato:
      type: object
      properties:
        dataEfetivacao:
          type: string
          description: Contract date
          example: 20220628
        statusContrato:
          type: string
          description: Status of the contract
          example: Ativo
          enum:
            - 'Ativo'
            - 'Inativo'
        indicadorAntecipacao:
          type: string
          description: Antecipation indicator
          example: Sim
          enum:
            - 'Sim'
            - 'Não'
        indicadorFraude:
          type: string
          description: Froud indicator
          example: Sim
          enum:
            - 'Sim'
            - 'Não'
        percentualReserva:
          type: string
          description: Froud indicator
          example: 1.00
      title: historicoContrato
