openapi: 3.0.2
info:
  description: Merchant Working Hours Update
  version: "1.0"
  title: Merchant Working Hours Update
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Merchant Working Hours Update
paths:
  "/bwa/wsm/merchantinformation/workingHours/updateWorkingHours/":
    post:
      tags:
        - Merchant Working Hours Update
      x-proxy-name: Merchant Working Hours - Update
      x-group-name: Merchant Information & Cases
      x-child-product-name: Digital Solutions
      description: Merchant Working Hours - Update
      summary: Merchant Information & Cases
      operationId: merchantWorkingHoursUpdate
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body"
        description: body
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
components:
  schemas:
    updateWorkingHours:
      type: object
      required:
        - institutionNumber
        - merchantID
        - weekDay
        - from
        - to
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        weekDay:
          type: string
          description: Week day
          example: Monday
          enum:
            - Monday
            - Sunday
            - Wednesday
            - Thrusday
            - Friday
            - Saturday
        from:
          type: string
          description: Merchant Opening Hours. Formato HHMM
          example: "0700"
        to:
          type: string
          description: Merchant Opening Hours. Formato HHMM
          example: "1900"
    Body:
      type: object
      properties:
        updateWorkingHours:
          type: array
          items:
            $ref: "#/components/schemas/updateWorkingHours"
    responseInformationList:
      type: object
      properties:
        responseCode:
          type: string
          description: Return Code
          example: "00"
          enum:
            - 00 - Successfully Done
            - 99 - System Error
        responseCodeDesc:
          type: string
          description: Return Code
          example: Successfully Done
          enum:
            - 00 - Successfully Done
            - 99 - System Error
    response:
      type: object
      properties:
        responseInformationList:
          type: array
          items:
            $ref: "#/components/schemas/responseInformationList"
    processMessage:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        weekDay:
          type: string
          description: Week Day to be update
          example: Monday
          enum:
            - Monday
            - Sunday
            - Wednesday
            - Thrusday
            - Friday
            - Saturday
        response:
          $ref: "#/components/schemas/response"
    Response:
      type: object
      properties:
        processMessage:
          type: array
          items:
            $ref: "#/components/schemas/processMessage"
    Unauthorized:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          type: integer
          example: 4
        mensagem:
          description: Description return code
          example: Acesso nao autorizado ao conteudo pesquisado - (meaning Unauthorized Access)
          type: string
