################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    sections:
    - title: Boarding
      link: docs/1-boarding.md
    - title: Logistitcs
      link: docs/2-logistics.md
    - title: Payments
      link: docs/3-payments.md
      sections:
      - title: Request Types
        link: docs/3-1-request-types.md
      - title: Payment Methods
        link: docs/3-2-payment-methods.md
      - title: Payment Types
        link: docs/3-3-payment-types.md
      - title: Post-authorisation & Returns
        link: docs/3-4-post-auth.md
      - title: 3-D Secure
        link: docs/3-5-3d-secure.md
      - title: Card Verification
        link: docs/3-6-card-verification.md
      - title: Currency Conversion
        link: docs/3-7-currency-conversion.md
      - title: Managed Redirect
        link: docs/3-8-managed-redirect.md
      - title: Orders
        link: 3-9-orders.md
      - title: Payment Url
        link: 3-10-payment-url.md
      - title: Recurring Payments
        link: 3-11-recurring-payments.md
      - title: Tokenisation
        link: 3-12-tokenisation.md
- sections:
  - title: November
    link: docs/release-notes/2022/november.md
