################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
#  productName: Merchant Acquiring - LATAM
#  image: 
#    link: "/assets/images/Fiserv_Logo.jpg"
#    altText: Fiserv
  productionDescription: Expand your business’ reach by taking the acceptance process to a different level. Merchants will expand their service and provide different experiences to their clients by leveraging new features and services at the point-of-sale, in real-time to increase their billing and usage.
getStarted: docs/english/getting-started.md
benefits:
  - title: Customized Solutions
    description: Whatever your business needs – be it full, semi or direct we've got your integration model.
  - title: End to End Value
    description: Create rewards programs for your merchants or develop loyalty apps for our Marketplace.
  - title: Work with the Best
    description: Dedicated specialists and industry experts who understand the complexities of your business.
featuredFeatures:
  - title: Boarding
    description:  Onboard merchants to start accepting payments online or in-store, and streamline your process for registering new terminals and equipment.
    relatedDocs:
      - relatedDoc: 
        title: Boarding
        description: Boarding end-to-end. 
        link: "/docs/english/boarding/1-boarding.md"
    relatedAPIs:
      - relatedAPI: 
        title: Create Application
        description: Saves the whole application data.
        type: "post"        
        path: "/api/v1/boarding"
  - title: Logistics
    description:  Request new terminals to expand merchant business, paper rolls to keep selling, terminal replacements, withdrawals and confirm status for your field services requests..
    relatedDocs:
      - relatedDoc: 
        title: Financial Institution
        description: Intended for financial institutions and acquirers providing merchant support
        link: "docs/english/logistics/2-1-financial-institution.md"
    relatedAPIs:
      - relatedAPI: 
        title: Cancel Order
        description: Cancel Order.
        type: "post"        
        path: "/v1/cancel-order"
  - title: Payments
    description:  Create a seamless and secure purchase experience across all online and digital channels by leveraging our comprehensive set of features that will enable you to accept all major payment methods and enhance your customer's online shopping experience
    relatedDocs:
      - relatedDoc: 
        title: Recurring Payments
        description: The payment schedules API allows you to create and manage a recurring payment schedule for an individual consumer.
        link: "docs/english/payments/3-11-recurring-payments.md"
    relatedAPIs:
      - relatedAPI: 
        title: Account Verification
        description: Use this to perform an account verification for a payment card or payment token
        type: "post"        
        path: "/account-verification"
