################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Merchants will provide different experiences to their customers by making it easy to use
getStarted: /docs/english/getting-started.md
benefits:
  - title: Customized Solutions
    description: Whatever your business needs – be it full, semi or direct we've got your integration model.
  - title: End to End Value
    description: Create rewards programs for your merchants or develop loyalty apps for our Marketplace.
  - title: Work with the Best
    description: Dedicated specialists and industry experts who understand the complexities of your business.
featuredFeatures:
  - title: Boarding
    groupName: Merchant Acquiring
    featured: true
    description: Onboard merchants to start accepting payments and streamline your process for registering new terminals and equipment.
    relatedDocs:
      - relatedDoc:
        title: Boarding
        link: "/docs/english/boarding/1-boarding.md"
    relatedAPIs:
      - relatedAPI: 
        title: Create Application
        type: "post"        
        path: "/api/v1/boarding"
  - title: Digital Solutions
    groupName: Merchant Acquiring
    featured: true
    description: More than 40 applications are coordinated for internal and external administration of services.
    relatedDocs:
      - relatedDoc: 
        title: Home
        link: "docs/english/digitalSolutions/HomepageEditada.md"
    relatedAPIs:
      - relatedAPI: 
        title: Get Resume
        type: "get"        
        path: "/bwa/cashflow/v1/resume"
  - title: Logistics
    groupName: Merchant Acquiring
    featured: true
    description: Request new terminals to expand merchant business
    relatedDocs:
      - relatedDoc: 
        title: Financial Institution
        link: "docs/english/logistics/2-logistics.md"
    relatedAPIs:
      - relatedAPI: 
        title: Cancel Order
        type: "post"        
        path: "/v1/cancel-order"
  - title: Payments
    groupName: Merchant Acquiring
    description:  Create a seamless and secure shopping experience across all online and digital channels. 
    relatedDocs:
      - relatedDoc: 
        title: Recurring Payments
        link: "docs/english/payments/3-payments.md"
    relatedAPIs:
      - relatedAPI: 
        title: Account Verification
        type: "post"        
        path: "/account-verification"
