################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Merchant Acquiring - LATAM
  productionDescription: Expand your business’ reach by taking the acceptance process to a different level. Merchants will expand their service and provide different experiences to their clients by leveraging new features and services at the point-of-sale, in real-time to increase their billing and usage.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv
featuredFeatures:
  - title: TBD
    description:  REPLACE ME
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["Hola", "REPLACEME" ]  
    relatedDocs:
      - relatedDoc: 
        title: Clover
        description: Add semi-integrated payments to your iOS, Android or Windows POS using our attractive Clover Mini or Go hardware.
        link: [Clover](https://www.clover.com/pos/integration-services)  
      - relatedDoc: 
        title: cardpointe
        description: Securely process a wide range of credit, debit and alternative payment options, for both card-present and card-not-present transactions, with our complete set of APIs. Simply manage all transactions from one place, with the comprehensive CardPointe platform.
        link: 
      - relatedDoc: 
        title: Rapid Connect
        description: One stop access to create, test, certify and deliver payment rich applications that seamlessly integrate to First Data Payment Systems.
        link:
      - relatedDoc: 
        title: App Market
        description: Develop Apps for the Clover Marketplace.
        link: 
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "post"        
        path: "/v1/REPLACEME2"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "get"        
        path: "/v1/REPLACEME3"
