################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Merchant Acquiring - LATAM
  productionDescription: Expand your business’ reach by taking the acceptance process to a different level. Merchants will expand their service and provide different experiences to their clients by leveraging new features and services at the point-of-sale, in real-time to increase their billing and usage.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv
featuredFeatures:
  - title: Online Payments
    description:  Create a seamless and secure purchase experience across all online and digital channels by leveraging our comprehensive set of features that will enable you to accept all major payment methods and enhance your customer's online shopping experience
    tags: ["Payments"]
    bullets: ["Payments"]  
    relatedDocs:
      - relatedDoc: 
        title: Recurring Payments
        description: The payment schedules API allows you to create and manage a recurring payment schedule for an individual consumer.
        link: "docs/english/payments/3-11-recurring-payments.md"
      - relatedDoc:
        title: 3-D Secure
        description: When using our Gateway and Fiserv as the 3-D Secure provider, the authentication is performed in-line with the existing transaction flow.
        link: "docs/english/payments/3-5-3d-secure.md"
      - relatedDoc: 
        title: Tokenisation
        description: Tokens are useful when storing the details of a customer’s payment instruments to secure and speed up checkout later.
        link: "docs/english/payments/3-12-tokenisation.md"
      - relatedDoc: 
        title: Payment URL
        description: Payment URL is a functionality that allows you to provide a link to your customers which then takes the customer to a Fiserv-hosted page to securely make the payment with their preferred payment method, whenever convenient for them.
        link: "docs/english/payments/3-10-payment-url.md"
    relatedAPIs:
      - relatedAPI: 
        title: Account Verification
        description: Use this to perform an account verification for a payment card or payment token
        type: "post"        
        path: "/account-verification"
      - relatedAPI: 
        title: URL Creation
        description: Use this to generate an embedding payment link.
        type: "post"        
        path: "/payment-url"
      - relatedAPI: 
        title: Token Creation
        description: Use this to create a payment token from a payment card.
        type: "post"        
        path: "/payment-tokens"
  - title: Merchant and Terminal Boarding
    description:  Onboard merchants to start accepting payments online or in-store, and streamline your process for registering new terminals and equipment.
    tags: ["Boarding"]
    bullets: ["Boarding"]  
    relatedDocs:
      - relatedDoc: 
        title: New Merchant Boarding Steps
        description: the steps of the journey to getting your merchant boarded. 
        link: "/docs/english/boarding/1-1-boarding-steps.md"
      - relatedDoc:
        title: Prerequisites
        description: One part of getting you on board is the configuration of ‘offers’ and the setting of these offers is essential for the onboarding process to work.
        link: "docs/english/boarding/1-2-prerequisites.md"
    relatedAPIs:
      - relatedAPI: 
        title: Create Application
        description: Saves the whole application data.
        type: "post"        
        path: "/api/v1/application"
      - relatedAPI: 
        title: Update Application
        description: Update the whole application data.
        type: "put"        
        path: "/api/v1/application/{id}"
      - relatedAPI: 
        title: New Terminal
        description: Adds a new terminal to an already boarded application.
        type: "post"        
        path: "/api/v1/application/{id}/terminals"
