openapi: 3.0.2
info:
  description: Prepayment Flag Update
  version: "1.0"
  title: Prepayment Flag Update
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Prepayment Flag Update
    description: Prepayment Flag Update
paths:
  "/bwa/wsm/fundingtools/prepayFlag/updatePrepayFlag":
    post:
      tags:
        - Prepayment Flag Update
      x-proxy-name: Service Order - Terminal Maintenance - Prepayment Flag Update (Turn On/Off)
      x-group-name: Payment & Prepayment Information
      x-child-product-name: Digital Solutions
      description: Prepayment Flag Update (Turn On/Off)
      summary: Prepayment Flag Update (Turn On/Off)
      operationId: PrepaymentFlagUpdate
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: ''
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: '1563309156733'
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body"
        description: Dados
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
components:
  schemas:
    merchants:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        prepaymentFlag:
          type: string
          description: Prepayment Flag Information
          example: "1 - Habilitar - (meaning Turn it On)"
          enum:
            - 1 - Habilitar - (meaning Turn it On)
            - 0 - Desabilitar - (meaning Turn it Off)
        effectiveDate:
          type: string
          description: Effective Start Date. Required when Flag = 1
          example: "DDMMAAAA"
        reservePercent:
          type: string
          description: "% of reservation. The amount that will not be available for prepayment. 3 Integer and 2 Decimals"
          example: "001.00"
        auditTrail:
          type: string
          description: Audit User Log Information. For userID contact your Fiserv Representative.  (Julian Date - Hour Minutes Seconds - User ID - Simple Description)
          example: "22179-100001-100999-AjustePrepFlag"
    Body:
      type: object
      properties:
        merchants:
          type: array
          items:
            $ref: "#/components/schemas/merchants"
    processMessage:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantId:
          type: string
          description: Merchant Code
          example: "91002806"
        statusCode:
          type: string
          example: "0 - Prepayment Flag Update"
          description: Return Code Description
          enum:
            - 0 - Prepayment Flag Update
            - 1 - Prepaypment Flag Already Set
            - 2 - Merchant Not Found
            - 3 - Invalid Effective Date
            - 4 - Effective Date Less Than Posting Date
            - 5 - Invalid Reserv Percentage
            - 8 - Mandatory Information Missing
            - 9 - System Error
    Response:
      type: object
      properties:
        processMessage:
          type: array
          items:
            $ref: "#/components/schemas/processMessage"
    Unauthorized:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          type: integer
          example: 4
        mensagem:
          description: Description return code
          example: Acesso nao autorizado ao conteudo pesquisado - (meaning Unauthorized Access)
          type: string
