openapi: 3.0.2
info:
  description: Search Device Operation
  version: "1.0"
  title: Search Device Operation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Search Device Operation
paths:
  /bwa/wsm/devicerequest/consultoperation/processConsultOperationRequest/:
    post:
      tags:
        - Search Device Operation
      x-proxy-name: Operations - Consult
      x-group-name: Sales Information
      x-child-product-name: Digital Solutions
      description: Operations - Consult
      summary: Search Device Operation
      operationId: searchDeviceOperation
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body"
        description: dadosAccounts
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
components:
  schemas:
    consultOperation:
      type: object
      required:
        - institutionNumber
        - merchantID
        - contactName
        - terminalID
        - tmsReferenceID
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        contactName:
          type: string
          description: Merchant Contact Name
          example: Mario de Almeida
        terminalID:
          type: string
          description: Device ID with 8 digits
          example: 12345678
        tmsReferenceID:
          type: string
          description: Device Reference ID with 12 digits
    Body:
      type: object
      properties:
        consultOperation:
          type: array
          items:
            $ref: "#/components/schemas/consultOperation"
    responseInformationList:
      type: object
      properties:
        responseCode:
          type: string
          description: Return Code
          example: "00"
          enum:
            - 00 - Successfully Done
            - 03 - Invalid Combination (Merchant ID, Device Id and Reference ID)
            - 99 - System Error
        responseCodeDesc:
          type: string
          description: Return Code Description
          example: Successfully Done
            - 00 - Successfully Done
            - 03 - Invalid Combination (Merchant ID, Device Id and Reference ID)
            - 99 - System Error
    tmsInformationList:
      type: object
      properties:
        tmsReferenceID:
          type: string
          description: Request Reference ID, with 12 digits
          example: 123456789012
    processMessage:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        tmsRequestNumber:
          type: string
          description: Request Number created, with 8 digits
          example: 12345678
        tmsDetails:
          type: array
          description: Reference Numbers List
          items:
            $ref: "#/components/schemas/tmsInformationList"
        response:
          $ref: "#/components/schemas/responseInformationList"
    Response:
      type: object
      properties:
        processMessage:
          type: array
          items:
            $ref: "#/components/schemas/processMessage"
    Unauthorized:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          type: integer
          example: 4
        mensagem:
          description: Description return code
          example: Acesso nao autorizado ao conteudo pesquisado - (meaning Unauthorized Access)
          type: string
