openapi: 3.0.2
info:
  description: Merchant Status Update
  version: "1.0"
  title: Merchant Status Update
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-header-api-key: 'X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
x-header-api-secret: 'N93nmFmoY0NzSMC5'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Merchant Status Update
    description: Merchant Status Update
paths:
  /bwa/wsm/fundingtools/contractStatus/updateContractStatus:
    post:
      tags:
        - Merchant Status Update
      x-proxy-name: Merchant Status Update
      x-group-name: Service Order Information
      x-child-product-name: Digital Solutions
      summary: Merchant Status Update
      operationId: merchantStatusUpdate
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example:
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body"
        description: body
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    merchants:
      type: object
      properties:
        auditTrail:
          type: string
          description: User ID responsible for the update. Please consult Fiserv Representative - short description
          example: "999999"
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "12345678"
        merchantStatus:
          type: string
          description: Merchant New Status
          example: "1"
          enum:
            - "1 - Ativo - (meaning Active)"
            - "2 - Inativo - (meaning Inactive)"
            - "3 - Suspenso - (meaning Suspended)"
            - "4 - Fechado - (meaning Closed)"
        reason:
          type: string
          description: Reason for the Status Update
          example: "01"
          enum:
            - 01 - Padrão - (meaning Operations - Default)
            - 02 - Inoperante - (meaning Inoperative)
            - 03 - Suspensão Fraude - (meaning Fraud Suspension)
            - 04 - Suspensão Risco - (meaning Risk Suspension)
            - 05 - Suspensão Requisição Cliente - (meaning Suspension customer request)
            - 06 - Suspensão Comercial - (meaning Suspension comercial request)
            - 07 - Encerramento Fraude (meaning Fraud - Closure)
            - 08 - Encerramento Risco - (meaning Risk Closure)
            - 09 - Encerramento Requisição Cliente - (meaning Closure customer request)
            - 10 - Encerramento Comercial - (meaning losureC comercial request)
    Body:
      type: object
      properties:
        merchants:
          type: array
          items:
            $ref: "#/components/schemas/merchants"
    processMessage:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Marchant Code
          example: "12345678"
        statusCode:
          type: string
          description: Return Code
          example: "0"
          enum:
            - 0 - Merchant status updated
            - 1 - Merchant status already set
            - 2 - Merchant not found
            - 3 - Invalid Merchant Status
            - 4 - Invalid Reason
            - 5 - No Response from Commserver/TMS/FHM
            - 6 - Request rejected by TMS/FHM
            - 8 - Mandatory Information missing
            - 9 - System error
    Response:
      type: object
      properties:
        processMessage:
          type: array
          items:
            $ref: "#/components/schemas/processMessage"
