openapi: 3.0.2
info:
  description: Bureau for Tax ID - Individual - CPF (SERPRO)
  version: "1.0"
  title: Bureau for Tax ID - Individual - CPF (SERPRO)
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-header-api-key: 'X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
x-header-api-secret: 'N93nmFmoY0NzSMC5'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Bureau for Tax ID - Individual - CPF (SERPRO)
paths:
  "/bwa/consulta-cpf/{cpf}":
    get:
      tags:
        - Bureau for Tax ID - Individual - CPF
      x-proxy-name: Tax ID (individual) Validation (not available PROD)
      x-group-name: Service Order Information
      x-child-product-name: Digital Solutions
      description: Bureau for Tax ID - Individual - CPF
      summary: Search Bureau for Individual Tax ID - CPF (SERPRO)
      operationId: searchIndividualTaxId
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: cpf
          in: path
          description: Individual Tax ID Number
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully Done.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
      deprecated: false
components:
  schemas:
    situacao:
      type: object
      properties:
        codigo:
          type: string
          description: Tax ID (CPF) Situation Code
          example: "0"
          enum:
            - 0 Regular - (meaning regular)
            - 2 Suspensa - (meaning suspendente)
            - 3 Titular Falecido - (meaning deceased)
            - 4 Pendente de Regularização - (meaning pending)
            - 5 Cancelada por Multiplicidade - (meaning cancelled)
            - 8 Nula - (meaning revoked)
            - 9 Cancelada de Ofício - (meaning cancelled by order)
        descricao:
          type: string
          description: Tax ID (CPF) Situation Description
          example: "Regular"
          enum:
            - 0 Regular - (meaning regular)
            - 2 Suspensa - (meaning suspendente)
            - 3 Titular Falecido - (meaning deceased)
            - 4 Pendente de Regularização - (meaning pending)
            - 5 Cancelada por Multiplicidade - (meaning cancelled)
            - 8 Nula - (meaning revoked)
            - 9 Cancelada de Ofício - (meaning cancelled by order)
      title: situacao
      description: Class representing the situation of the CPF
    Response:
      type: object
      properties:
        ni:
          type: string
          description: Tax ID (CPF) searched.
        nome:
          type: string
          description: Name responsible for the Tax ID (CPF)
        situacao:
          $ref: "#/components/schemas/situacao"
      title: Response
      description: Class representing returning search Zip Code
