openapi: 3.0.2
info:
  description: Geo Localion WebService (Google)
  version: "1.0"
  title: Geo Location WebService (Google)
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-header-api-key: 'X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
x-header-api-secret: 'N93nmFmoY0NzSMC5'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Geo Location
    description: Geo Location
paths:
  "/bwa/geocode/{address}":
    get:
      tags:
        - Geo Location
      x-proxy-name: Geo Location
      x-group-name: Service Order Information
      x-child-product-name: Digital Solutions
      summary: Get the Geo Location based on provided address
      operationId: searchGeocode
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example:
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: address
          in: path
          description: Address to be found in the service
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddressResponse"
components:
  schemas:
    Northeast:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
    Southwest:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
    Bounds:
      type: object
      properties:
        northeast:
          $ref: "#/components/schemas/Northeast"
        southwest:
          $ref: "#/components/schemas/Southwest"
    Location:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
    Viewport_Northeast:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
    Viewport_Southwest:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
    Viewport:
      type: object
      properties:
        northeast:
          $ref: "#/components/schemas/Viewport_Northeast"
        southwest:
          $ref: "#/components/schemas/Viewport_Southwest"
    Geometry:
      type: object
      properties:
        bounds:
          $ref: "#/components/schemas/Bounds"
        location:
          $ref: "#/components/schemas/Location"
        viewport:
          $ref: "#/components/schemas/Viewport"
        location_type:
          type: string
    Address_components:
      type: object
      properties:
        types:
          type: array
          items:
            type: string
        long_name:
          type: string
        short_name:
          type: string
    Results:
      type: object
      properties:
        geometry:
          $ref: "#/components/schemas/Geometry"
        types:
          type: array
          items:
            type: string
        address_components:
          type: array
          items:
            $ref: "#/components/schemas/Address_components"
        formatted_address:
          type: string
        place_id:
          type: string
    Geocode:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/Results"
        status:
          type: string
    AddressResponse:
      type: object
      properties:
        codigoRetorno:
          type: integer
          format: int32
        descricaoRetorno:
          type: string
        geocode:
          $ref: "#/components/schemas/Geocode"
