openapi: 3.0.0
info:
  description: Search for ZIPCODE and Citi (Brazil)
  version: "1.0"
  title: Search for ZIPCODE and Citi (Brazil)
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Search Zipcode or City (Brazil)
    description: Search Zipcode or City (Brazil)
paths:
  "/bwa/cep-service/cep/{cep}":
    get:
      tags:
        - Search Zipcode or City (Brazil)
      x-proxy-name: Zipcode (CEP) - Consult
      x-group-name: Service Order Information
      x-child-product-name: Digital Solutions
      description: Search ZIPCODE (Brazil)
      summary: Search ZIPCODE (Brazil)
      operationId: searchZipcode
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: ''
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: '1563309156733'
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: cep
          in: path
          description: ZIPCODE to be searched
          example: "05056000"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully Done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCode"
        "401":
          description: Token not Provided or Expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCode"
      deprecated: false
  "/bwa/cep-service/cidade/{city}":
    get:
      tags:
        - Search Zipcode or City (Brazil)
      x-proxy-name: Zipcode (CEP) - Consult - Search for City Name
      x-group-name: Service Order Information
      x-child-product-name: Digital Solutions
      description: Search for City Name
      summary: Search for City Name
      operationId: searchForCityName
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: ''
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: '1563309156733'
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: city
          in: path
          description: City Name to be Searched
          example: "Sao Paulo"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully Done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCodeCity"
        "401":
          description: Token not Provided or Expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCodeCity"
      deprecated: false
components:
  schemas:
    CepResponse:
      type: object
      properties:
        address:
          type: string
          description: ZIPCODE Address
          example: Rua das Acacias
        city:
          type: string
          description: ZIPCODE City
          example: Cidade das Acacias
        complement:
          type: string
          description: Address Complement
          example: Apartamento 11
        genericZipCode:
          type: string
          description: Information whether ZIPCODE is generic or not
          example: "Sim"
          enum:
            - "Sim"
            - "Não"
        neighborhood:
          type: string
          description: ZIPCODE Neighborhood.
          example: Vila das Acacias
        state:
          type: string
          description: ZIPCODE State
          example: SP
        zipCode:
          type: string
          description: ZIPCODE
          example: "05056020"
      title: CepResponse
      description: ZIPCODE Information
    ResponseCode:
      type: object
      required:
        - code
        - description
      properties:
        cepResponse:
          $ref: "#/components/schemas/CepResponse"
        code:
          type: string
          description: Return Code
          example: "00 - Successfully Done"
          enum:
            - "00 - Successfully Done"
            - "99 - System Error"
        description:
          type: string
          description: Return description
          example: "00 - Successfully Done"
          enum:
            - "00 - Successfully Done"
            - "99 - System Error"
      title: ResponseCode
      description: Class representing returning search Zip Code
    listResponseCityState:
      properties:
        state:
          type: string
          description: State Name Abbreviation. Multiple Return
          example: "SP"
        city:
          type: string
          description: City Name. Multiple Return
          example: São Paulo
    ResponseCodeCity:
      type: string
      properties:
        code:
          type: string
          description: Return Code
          example: "00 - Successfully Done"
          enum:
            - "00 - Successfully Done"
            - "99 - System Error"
        description:
          type: string
          description: Return Description
          example: "00 - Successfully Done"
          enum:
            - "00 - Successfully Done"
            - "99 - System Error"
        cepResponse:
          type: array
          oneOf:
            - $ref: "#/components/schemas/listResponseCityState"
      title: ResponseCode
      description: Class representing returning search Zip Code
